[workspace]

members = [
  "candy-core/program",
  "candy-guard/program"
]

exclude = [
  "auction/program",
  "auction-house/program",
  "bubblegum/program",
  "candy-machine/program",
  "candy-wrapper/program",
  "fixed-price-sale/cli",
  "fixed-price-sale/program",
  "metaplex/program",
  "nft-packs/program",
  "token-entangler/program",
  "token-metadata",
  "token-vault/program",
  "token-vault/test"
]
